import { cleanProductName } from "../../src";

describe("Product Name Cleaner", () => {
  const testData: [string, string][] = [
    // 1 - passed
    ["VIP War Horse - WeAreDiscGolf.no", "war horse"],
    ["Opto Stiletto - Krokhol Disc Golf Shop", "stiletto"],
    ["Dragon Line Shu", "shu"],
    ["Big Z Athena Paul McBeth", "athena"],
    ["Classic Burst Warden Blend - WeAreDiscGolf.no", "warden"],
    ["S-Line Swirly FD - WeAreDiscGolf.no", "fd"],
    ["Undertaker", "undertaker"],
    ["F3 500 - Ring of Stars Stamp", "f3"],
    ["Innova First Run Star Alien", "star alien"],
    ["Ethos Synapse", "synapse"],
    ["Cosmic Neutron Entropy - Krokhol Disc Golf Shop", "entropy"],
    ["K1 Grym", "grym"],
    ["Opto Flow - WeAreDiscGolf.no", "flow"],
    ["K1 Vass", "vass"],
    ["S-Line DD - DiscShopen.no", "dd"],
    ["Wizard Super Soft - WeAreDiscGolf.no", "wizard"],

    // 2 - passed
    ["ESP Nuke Solid White Bottom Stamp - WeAreDiscGolf.no", "nuke"],
    ["Axiom Electron Proxy Soft - Aceshop", "proxy"],
    ["Grand Trust", "trust"],
    ["Neo Essence Primal Run - WeAreDiscGolf.no", "essence"],
    ["Opto Air Explorer - WeAreDiscGolf.no", "explorer"],
    ["C-Line Color Glow FD2 Royal Rage - WeAreDiscGolf.no", "fd2"],
    ["Ground Warrior - WeAreDiscGolf.no", "ground warrior"],
    ["Special Blend S-Line CD1 Zeta's Moon - Colten Montgomery Signatu", "cd1"],
    ["Star Wraith Bottom Stamp", "star wraith"],
    ["Storm Cosmos - WeAreDiscGolf.no", "storm cosmos"],
    ["Halo Star Invader", "invader"],
    ["BioFuzion Justice - Krokhol Disc Golf Shop", "justice"],
    ["Big Z Zeus Paul McBeth", "zeus"],
    ["H7", "h7"],
    ["300 Plastic M3 - Krokhol Disc Golf Shop", "m3"],
    ["Blizzard Champion Ape", "ape"],

    // 3 - passed
    ["Plasma Octane", "octane"],
    ["Nebula Ethereal Omen", "omen"],
    ["Muse [Nerve] | Spinnvill", "muse"],
    ["Alpha Texas Ranger", "alpha texas ranger"],
    ["VIP Queen - WeAreDiscGolf.no", "queen"],
    ["Bravo Guadalupe", "guadalupe"],
    [
      "Electron Envy - James Conrad Team Signature Series - Krokhol Disc Golf Shop",
      "envy",
    ],
    ["Halo Star AviarX3 - WeAreDiscGolf.no", "aviarx3"],
    ["Airborn Stryder 400 - Proto Stamp", "stryder"],
    ["Classic Judge Soft - WeAreDiscGolf.no", "judge"],
    ["Z Nuke Blue Bomber Aaron Gossage", "nuke"],
    ["Lucid Air Trespass", "trespass"],
    ["Snoopy Stock Stamp/First Run Butikk", "snoopy"],
    ["ESP Anax, Paul Mcbeth", "anax"],
    ["S-Line P1 - WeAreDiscGolf.no", "p1"],
    ["Proton Inertia", "inertia"],

    // 4 - passed
    ["Neutron Switch - WeAreDiscGolf.no", "switch"],
    ["Opto Jade - DiscShopen.no", "jade"],
    ["Pro Boss", "pro boss"],
    ["CRAVE Fission - Frisbeesor.no", "crave"],
    ["Star Beast - WeAreDiscGolf.no", "star beast"],
    ["Z LINE FLY DYE ZONE - Frisbeesor.no", "zone"],
    ["Cosmic Piwakawaka - WeAreDiscGolf.no", "cosmic piwakawaka"],
    ["Star Cro - WeAreDiscGolf.no", "star cro"],
    ["DX Sonic", "sonic"],
    ["Opto Pioneer", "pioneer"],
    ["XT Stud - WeAreDiscGolf.no", "stud"],
    ["F1 500 Spectrum Plastic - Ezra Robinson 2023", "f1"],
    ["Protege Clutch - WeAreDiscGolf.no", "clutch"],
    ["DX Aviar PT & AP - Krokhol Disc Golf Shop", "aviar"],
    ["400 F1 - WeAreDiscGolf.no", "f1"],
    ["OG Firm Phi - WeAreDiscGolf.no", "phi"],

    // 5 - passed
    ["Halo Star Roadrunner - Frisbeesor.no", "roadrunner"],
    ["K1 Berg Glow 2022 - WeAreDiscGolf.no", "berg"],
    ["Divergent Narwhal", "narwhal"],
    ["D1 Kraken Stamp", "d1"],
    ["X5", "x5"],
    ["Team Aceshop Star Wraith", "star wraith"],
    ["X Mantis - WeAreDiscGolf.no", "mantis"],
    ["Retro Burst Fuse X-Out - WeAreDiscGolf.no", "fuse"],
    ["M4 300", "m4"],
    ["Genius Active Premium Driver Discmania - GolfKongen", "genius"],
    ["Bravo BB6 - Artist Series", "bb6"],
    ["Big Z Roach fra Discraft - Krokhol Disc Golf Shop", "roach"],
    ["C-Blend Metal Flake Glow Chariot X-Out - WeAreDiscGolf.no", "chariot"],
    ["Rask 2021 glow", "rask"],
    [
      "Opto-X Glimmer Explorer - Emerson Keith Team Series 2021 - Frisbeesor.no",
      "explorer",
    ],
    ["Z Buzzz OS", "buzzz os"],

    // 6 - passed
    ["Z Nuke Glo - WeAreDiscGolf.no", "nuke"],
    ["Star Caiman First Run - WeAreDiscGolf.no", "star caiman"],
    ["Prodigy 400 A1 X-Out", "a1"],
    ["Z Force - WeAreDiscGolf.no", "force"],
    ["Lux Vapor Mutant Special Edition", "mutant"],
    ["Glacier Line Mad Mission Midrange Guru - GolfKongen", "mad mission"],
    ["Star Rat", "star rat"],
    [
      "NORDIC PHENOM - NIKLAS ANTTILA SIGNATURE SERIES S-LINE PD - Frisbeesor.no",
      "pd",
    ],
    ["Total Eclipse Proxy - Special Edition - Krokhol Disc Golf Shop", "proxy"],
    ["Jawbreaker Banger GT - WeAreDiscGolf.no", "banger gt"],
    ["Reverb [400] | Spinnvill", "reverb"],
    ["VIP Sling - WeAreDiscGolf.no", "sling"],
    ["S-Line Vanguard Kylie Klein - WeAreDiscGolf.no", "vanguard"],
    ["K1 Lots - Moomin - Krokhol Disc Golf Shop", "lots"],
    ["I-Blend Chariot - WeAreDiscGolf.no", "chariot"],
    ["Steady Ginger - WeAreDiscGolf.no", "ginger"],

    // 7 - passed
    ["K1 Svea Glow 2022 - WeAreDiscGolf.no", "svea"],
    ["Zero Soft Pure", "pure"],
    ["FD", "fd"],
    ["UV Z Wasp", "wasp"],
    ["Champion Driver Teebird3", "teebird3"],
    ["M4 400G", "m4"],
    ["OG Soft Penrose - Krokhol Disc Golf Shop", "penrose"],
    ["500 X3 - Aceshop", "x3"],
    ["Plasma Fireball", "fireball"],
    ["Opto Air River - Krokhol Disc Golf Shop", "river"],
    ["KC Pro Aviar", "kc pro aviar"],
    ["Champion Glow Gator3 Joel Freeman 2022 - Aceshop", "gator3"],
    ["Gold Explorer Mini Stamp - WeAreDiscGolf.no", "explorer"],
    ["Tournament Underworld - WeAreDiscGolf.no", "underworld"],
    ["Lucid Warrant - WeAreDiscGolf.no", "warrant"],
    ["Big Z Zeus fra Discraft - Krokhol Disc Golf Shop", "zeus"],

    // 8 - passed
    ["Cloud Breaker Horizon Eagle Mcmahon Series", "cloud breaker"],
    ["Blizzard Champion Wraith", "wraith"],
    ["Star Destroyer Discboyz - WeAreDiscGolf.no", "star destroyer"],
    ["C-Line FD3 Jackal Stamp", "fd3"],
    ["Electron Anode Firm", "anode"],
    ["Zero Burst Spike Soft", "spike"],
    ["ESP McBeth signature Zeus - Frisbeesor.no", "zeus"],
    ["Phoenix Line Shu", "shu"],
    ["ESP Buzzz SS - Krokhol Disc Golf Shop", "buzzz ss"],
    ["K3 Hard Berg", "berg"],
    ["Big Z Athena fra Discraft - Krokhol Disc Golf Shop", "athena"],
    ["Star Alien", "star alien"],
    // ["dgputt pakke - BT Swan2 Medium - 5 pakk - Aceshop", ""],
    ["Z Meteor Glo - WeAreDiscGolf.no", "meteor"],
    ["Fission Hex", "hex"],
    // ["dgputt pakke - Electron Pilot Firm - 3 pakk - Aceshop", ""],

    // 9 -
    ["ESP FLX Zone", "zone"],
    ["Star Lion INNfuse - Aceshop", "star lion"],
    ["Champion Gator3 Joel Freeman 2021 - WeAreDiscGolf.no", "gator3"],
    ["Star Destroyer Discboyz - WeAreDiscGolf.no", "star destroyer"],
    ["BT Swan Soft X-Out - WeAreDiscGolf.no", "swan"],
    ["Champion Teebird Luster Two Color Air Force Stamp", "teebird"],
    ["S-Line FD1 - Krokhol Disc Golf Shop", "fd1"],
    ["FD3 S-Line Doom Bird Simon Lizotte", "fd3"],
    [
      "MVP Eclipse 2.0 Reactor Elaine King 5xSignature Series - Frisbeesor.no",
      "reactor",
    ],
    ["Zero Pure Hard", "pure"],
    ["Ethos Construct - WeAreDiscGolf.no", "construct"],
    ["A2 [750] | Spinnvill", "a2"],
    [
      "Star Firebird Shimmer Two Color Air Force - WeAreDiscGolf.no",
      "star firebird",
    ],
    ["SL Neutron Flare - Aceshop", "flare"],
    ["Discraft Z Force Andrew Presnell 2021", "force"],
    ["S-Line FD3", "fd3"],
  ];

  test.each(testData)(
    "cleanProductName(%s) should return %s",
    (input, expected) => {
      const actual = cleanProductName(input);

      expect(actual).toBe(expected);
    }
  );
});
