export const blacklist = [
  " -",
  ",",
  ".",
  "- ",
  "�",

  // Years + future proofing
  "2028",
  "2027",
  "2026",
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",

  // MPO names
  "Gannon Buhr",
  "Calvin Heimburg",
  "Isaac Robinson",
  "Richard Wysocki",
  "Simon Lizotte",
  "Matthew Orum",
  "Kyle Klein",
  "Eagle McMahon",
  "Anthony Barela",
  "Chris Dickerson",
  "Paul McBeth",
  "James Proctor",
  "Alden Harris",
  "Niklas Anttila",
  "Cole Redalen",
  "Ezra Robinson",
  "Ezra Aderhold",
  "James Conrad",
  "Joel Freeman",
  "Adam Hammes",
  "Corey Ellis",
  "Kevin Jones",
  "Chris Clemons",
  "Väinö Mäkelä",
  "Benjamin Callaway",
  "Bradley Williams",
  "Mason Ford",
  "Emerson Keith",
  "Aaron Gossage",
  "Andrew Presnell",
  "Evan Smith",
  "Austin Turner",
  "Gavin Babcock",
  "Paul Ulibarri",
  "Andrew Marwede",
  "Joona Heinänen",
  "Nikko Locastro",
  "Garrett Gurthie",
  "Brodie Smith",
  "Robert Burridge",
  "Zach Arlinghaus",
  "Matt Bell",
  "Evan Scott",
  "Jake Hebenheimer",
  "Jeremy Koling",
  "Aidan Scott",
  "Eric Oakley",
  "Chandler Kramer",
  "Jakub Semerád",
  "Parker Welck",
  "Silas Schultz",
  "Nathan Sexton",
  "Luke Taylor",
  "Drew Gibson",
  "Andrew Fish",
  "Luke Humphries",
  "Gavin Rathbun",
  "Gregg Barsby",
  "Sullivan Tipton",
  "Albert Tamm",
  "Jake Monn",
  "Tristan Tanner",
  "Paul Oman",
  "Kevin Kiefer III",
  "Grady Shue",
  "Raven Newsom",
  "Casey White",
  "Linus Carlsson",
  "Austin Hannum",
  "Scott Withers",
  "Thomas Gilbert",
  "Chandler Fry",
  "Luke Samson",
  "Ty Love",
  "AJ Carey",
  "Dylan Seppala",
  "G.T. Hancock",
  "Tuomas Hyytiäinen",
  "Micah Groth",
  "Joseph Anderson",
  "Nathan Queen",
  "Braeden Sides",
  "Mason Marchbanks",
  "Colten Montgomery",
  "Ben Wolff",
  "Connor O'Reilly",
  "Nick Newton",
  "Nate Hecker",
  "Jared Stoll",
  "Tim Barham",
  "Garett Everson",
  "Max Regitnig",
  "Zachary Nash",
  "Cody Kirkland",
  "Randon Latta",
  "Harry Chace",
  "Clay Edwards",
  "Zackeriath Johnson",
  "Joshua Anthon",
  "Nick Hanson",
  "Jake Wolff",
  "Fredy Meza",
  "Noah Meintsma",
  "Clint Calvin",
  "Justin Rosak",
  "philo brathwaite",
  "Øyvind Jarnes",
  "David Feldberg",

  // FPO names
  "Kristin Tattar",
  "Ohn Scoggins",
  "Missy Gannon",
  "Catrina Allen",
  "Hailey King",
  "Holyn Handley",
  "Kat Mertsch",
  "Valerie Mandujano",
  "Ella Hansen",
  "Henna Blomroos",
  "Paige Pierce",
  "Macie Velediaz",
  "Sarah Hokom",
  "Eveliina Salonen",
  "Jessica Weese",
  "Natalie Ryan",
  "Maria Oliva",
  "Jennifer Allen",
  "Emily Beach",
  "Ali Smith",
  "Stacie Rawnsley",
  "Sai Ananda",
  "Deann Carey",
  "Heidi Laine",
  "Madison Walker",
  "Aria Castruita",
  "Juliana Korver",
  "Rebecca Cox",
  "Lisa Fajkus",
  "Vanessa Van Dyken",
  "Silva Saarinen",
  "Alexis Mandujano",
  "Keiti Tätte",
  "Paige Shue",
  "Holly Finley",
  "Lykke Lorentzen",
  "Cynthia Ricciotti",
  "Anniken Kristiansen Steen",
  "Hanna Huynh",
  "Stacie Kiefer",
  "Raven Klein",
  "Erika Stinchcomb",
  "Alex Benson",
  "Sarah Gilpin",
  "Stephanie Vincent",
  "Jordan Lynds",
  "Ellen Widboom",
  "Kona Star Montgomery",
  "Leah Tsinajinnie",
  "Dani Kleidon",
  "Hannah Manis",
  "Cadence Burge",
  "Lydia Cochran",
  "Morgan Lynds",
  "Chantel Budinsky",
  "Casey Pennington",
  "Callie McMorran",
  "Sandra Richardson",
  "Ratana Meekham",
  "Alexis Kerman",
  "Shelbi Dutton",
  "Lindsay Fish",
  "Violet Main",
  "Carli Charron",
  "Melody Castruita",
  "Katie Belty",
  "Emma Arp",
  "Katka Bodová",
  "Alyssa Pierson",
  "Emily Yale",
  "Kristine King",
  "Ellie Bryant",
  "Tiger Borth",
  "Hannah Stefanovich",
  "Chelsea Howells",
  "Karissa Dedmon",

  // retailers
  "aceshop",
  "wearediscgolf.no",
  "golfkongen",
  "westside discs",
  "krokhol disc golf shop",
  "spinnvill",

  // etc
  "founders edition",
  "Special Edition",
  "limited edition",
  "Signature Series",
  "tour series",
  "world champion",
  "7x",
  "6x",
  "5x",
  "4x",
  "3x",
  "2x",
  "midrange",
  "fairway",
  "distance",
  "driver",
  "fly dye",
  "fundraiser",
  "heatland",
  "prototype",
  "Approach",
  "putt",
  "assortert",
  "farge",
  "x-out",
  "air force",
  "worlds",
  "dyemax",
  "Captain America",
  "170+ carat",
  "mini stamp",
  "twisted flyer",
  "sparkle",
  "ledgestone",
  "lite",
  "commemorative",
  "InVision",
  "InnVision",
  "Originals",
  "CrushBoys",
  "Crush Boys",
  "misprint",
  "first run",
  "Smuggler's Pursuit",

  // manufacturers
  "discmania",
  "discraft",
  "innova",
  "latitude64",
  "dynamic discs",
  "infinite",
  "guru",

  // plastics
  "esp",
  "z-line",
  "z line",
  "evolution",
  "neo",
  "exo",
  "big-z",
  "big z",
  "active premium",
  "premium active",
  "jawbreaker",
  "titanium",
  "lucid",
  "gold",
  "crystal flx",
  "k1",
  "bt burst",
  "pure white",
  "firm",
  "crystal line",
  "putter line",
  "champion",
  "jk pro",
  "opto ice",
  "opto-x",
  "opto",
  "Alpha-Solid",
  "innfuse",
  "dragon line",
  "c-line",
  "d-line",
  "p-line",
  "vortex line",
  "glacier line",
  "zero medium",
  "zero hard",
  "i-blend",
  "d-blend",
  "classic blend",
  "retro burst",
  "royal grand",
  "prime burst",
  "flx",
  "bt soft",
  "ice orbit",
  "glimmer",
  "metal flake",
  "atomic",
  "Raptor Eye",
  "flex2",
  "omega4",
  "Dancing Bears",
  "(Bear)",
  "Authorized dealer",
  "Teddy Bear",
  "reprocessed",
  "huk lab",
  "flylife",
  "400 spectrum",
  "500 spectrum",
  "big stamp",
  "Flex 3",

  // bags
  "bx3",
  "ax5",
  "cx1",
].map((w) => w.toLowerCase());
