export const TEST_DATA: [string, string[]][] = [
  ["Big Z Buzzz - Aceshop", ["buzzz"]],
  ["Active Premium Maestro - Aceshop", ["maestro"]],
  ["SL Neutron Jet - Aceshop", ["jet"]],
  ["400 M1 - Aceshop", ["m1"]],
  ["MVP Neutron Zenith Special Edition - Aceshop", ["zenith"]],
  ["Innova DX Leopard", ["leopard"]],
  ["BIG Z undertaker - Aceshop", ["undertaker"]],
  ["SL Proton Jet Special Edition - Aceshop", ["jet"]],
  ["MVP Neutron Terra Blank - Aceshop", ["terra"]],
  [
    "Meta Tactic Razor Claw 3 Eagle McMahon Signature Series - Aceshop",
    ["tactic"],
  ],
  ["Pro Destroyer - Aceshop", ["destroyer"]],
  ["Star Lion INNfuse - Aceshop", ["lion"]],
  ["Ledgestone ESP Tour Series LSWT Undertaker - Aceshop", ["undertaker"]],
  ["Discmania Evolution Exo Tactic Hard - Aceshop", ["tactic"]],
  ["K3 Järn - Aceshop", ["jarn"]],
  ["ESP ZONE 6x Paul McBeth Signature Series - Aceshop", ["zone"]],
  ["MVP Neutron Zenith - Aceshop", ["zenith"]],
  ["PAUL MCBETH ZEUS DRIVER - Aceshop", ["zeus"]],
  ["ESP BUZZZ PAUL MCBETH SIGNATURE SERIES - Aceshop", ["buzzz"]],
  ["ESP BUZZZ SS - Aceshop", ["buzzz-ss"]],
  ["ESP AVENGER SS PAUL MCBETH SIGNATURE SERIES - Aceshop", ["avenger-ss"]],
  ["MVP Plasma Nomad - Aceshop", ["nomad"]],
  ["Glacier Flow Motion", ["flow-motion"]],
  ["Z LINE CRANK - Aceshop", ["crank"]],
  ["Innova R-Pro Rhyno", ["rhyno"]],
  ["Z-LINE RAPTOR - Aceshop", ["raptor"]],
  ["S-Line PD - Aceshop", ["pd"]],
  ["K1 GØTE - Aceshop", ["gote"]],
  ["K1 Kaxe - Aceshop", ["kaxe"]],
  ["Star Toro Calvin Heimburg - Aceshop", ["toro"]],
  ["Z-Line Buzzz SS - Aceshop", ["buzzz-ss"]],
  ["Z-Line Fly Dye Buzzz - Aceshop", ["buzzz"]],
  ["C-Line PD - Aceshop", ["pd"]],
  ["K1 Grym - Aceshop", ["grym"]],
  ["Axiom Cosmic Neutron Envy - Aceshop", ["envy"]],
  ["K3 Kaxe Z - Aceshop", ["kaxe-z"]],
  ["K1 Rask - Aceshop", ["rask"]],
  ["K1 Reko - Aceshop", ["reko"]],
  ["K1 Stål - Aceshop", ["stal"]],
  ["XT Nova - Aceshop", ["nova"]],
  ["K3 Berg - Aceshop", ["berg"]],
  ["DX Archangel - Aceshop", ["archangel"]],
  ["Axiom Neutron Tantrum - Aceshop", ["tantrum"]],
  ["Chrome Line Cosmic - Aceshop", ["cosmic"]],
  ["Champion Panther - Aceshop", ["panther"]],
  ["Active Premium Mentor - Aceshop", ["mentor"]],
  ["Z-Line Buzzz 20th Anniversary - Aceshop", ["buzzz"]],
  ["Jawbreaker Luna Paul McBeth - Aceshop", ["luna"]],
  ["ESP Raptor - Aceshop", ["raptor"]],
  ["Paige Pierce Fierce - Aceshop", ["fierce"]],
  ["XT Mako3 - Aceshop", ["mako3"]],
  ["Dx RocX3 - Aceshop", ["rocx3"]],
  ["Pro Wraith - Aceshop", ["wraith"]],
  ["DX Aviar PT & AP - Aceshop", ["aviar"]],
  ["Champion Firebird - Aceshop", ["firebird"]],
  ["Champion Mako3 - Aceshop", ["mako3"]],
  ["Champion Roc3 - Aceshop", ["roc3"]],
  ["DX Gator - Aceshop", ["gator"]],
  ["Axiom Proton Mayhem - Aceshop", ["mayhem"]],
  ["ESP FLX Raptor - Aceshop", ["raptor"]],
  ["Champion Orc - Aceshop", ["orc"]],
  ["Champion Eagle - Aceshop", ["eagle"]],
  ["Champion Teebird3 Metal Flake - Aceshop", ["teebird3"]],
  ["Champion RocX3 - Aceshop", ["rocx3"]],
  ["G-Star Thunderbird - Aceshop", ["thunderbird"]],
  ["R-Pro Pig - Aceshop", ["pig"]],
  ["Star Aviar - Aceshop", ["aviar"]],
  ["DX Wraith Glow - Aceshop", ["wraith"]],
  ["Star Destroyer - Aceshop", ["destroyer"]],
  ["Star Roadrunner Gregg Barsby - Aceshop", ["roadrunner"]],
  ["Star Teebird - Aceshop", ["teebird"]],
  ["Star Beast - Aceshop", ["beast"]],
  ["Star Aviar3 - Aceshop", ["aviar3"]],
  ["Star boss - Aceshop", ["boss"]],
  ["Star Teebird3 - Aceshop", ["teebird3"]],
  ["Pro Beast - Aceshop", ["beast"]],
  ["Discmania Active Premium Mentor", ["mentor"]],
  ["Star Thunderbird - Aceshop", ["thunderbird"]],
  ["Star RocX3 - Aceshop", ["rocx3"]],
  ["Star Shryke - Aceshop", ["shryke"]],
  ["BT Shield Hard - Aceshop", ["shield"]],
  ["Gold Fuse - Aceshop", ["fuse"]],
  ["Gold Ballista Pro - Aceshop", ["ballista-pro"]],
  ["BT Shield Medium - Aceshop", ["shield"]],
  ["Gold Diamond - Aceshop", ["diamond"]],
  ["Evolution Neo Paradigm - Aceshop", ["paradigm"]],
  ["Gold Claymore - Aceshop", ["claymore"]],
  [
    "Cosmic Fury - Kyle Klein Signature Series Lux Vapor Logic - Aceshop",
    ["logic"],
  ],
  ["Discraft Z Crank", ["crank"]],
  ["Gold Jade - Aceshop", ["jade"]],
  ["BT Burst Harp Medium - Aceshop", ["harp"]],
  ["Gold Ballista - Aceshop", ["ballista"]],
  ["BT Maiden Medium - Aceshop", ["maiden"]],
  ["Gold Compass - Aceshop", ["compass"]],
  ["BT Harp Medium - Aceshop", ["harp"]],
  ["5X PAIGE PIERCE Z UNDERTAKER - Aceshop", ["undertaker"]],
  ["Gold Saint - Aceshop", ["saint"]],
  ["TITANIUM ZONE - Aceshop", ["zone"]],
  ["Classic Judge - Aceshop", ["judge"]],
  ["Lucid Judge - Aceshop", ["judge"]],
  ["Fuzion EMAC Truth - Aceshop", ["emac-truth"]],
  ["Fuzion Felon - Aceshop", ["felon"]],
  ["Lucid EMAC Truth - Aceshop", ["emac-truth"]],
  ["Alpha-Solid Xenon - Aceshop", ["xenon"]],
  ["Lucid Justice - Aceshop", ["justice"]],
  ["Lucid Trespass - Aceshop", ["trespass"]],
  ["SL Neutron Flare - Aceshop", ["flare"]],
  ["ESP Buzzz OS Paige Pierce Signature Series - Aceshop", ["buzzz-os"]],
  ["Halo Star Roc3 - Aceshop", ["roc3"]],
  ["Star Jay - Aceshop", ["jay"]],
  ["Royal Sense Dagger - Aceshop", ["dagger"]],
  ["2023 Brodie Smith Tour Series Zone OS - Aceshop", ["zone"]],
  ["Opto Sapphire - Aceshop", ["sapphire"]],
  ["Opto Saint - Aceshop", ["saint"]],
  ["Star Rat - Aceshop", ["rat"]],
  ["Star Orc - Aceshop", ["orc"]],
  ["Star Tern - Aceshop", ["tern"]],
  ["Wizard Super soft - Aceshop", ["wizard"]],
  ["Opto River - Aceshop", ["river"]],
  ["ESP Venom - Aceshop", ["venom"]],
  ["K1 Falk Soft - Aceshop", ["falk"]],
  ["Champion Destroyer - Aceshop", ["destroyer"]],
  ["DX Roc - Aceshop", ["roc"]],
  ["K1 Svea - Aceshop", ["svea"]],
  ["Active Maestro - Aceshop", ["maestro"]],
  ["Voodoo Super soft - Aceshop", ["voodoo"]],
  ["Crystal FLX Zone Brodie Smith - Aceshop", ["zone"]],
  ["Champion Wraith - Aceshop", ["wraith"]],
  ["K1 Kaxe Z soft - Aceshop", ["kaxe-z"]],
  ["DX Leopard - Aceshop", ["leopard"]],
  ["DX Invader - Aceshop", ["invader"]],
  ["K1 Kaxe Soft - Aceshop", ["kaxe"]],
  ["Discmania Evolution Exo Link Soft - Aceshop", ["link"]],
  ["Z-Line Zone - Aceshop", ["zone"]],
  ["K1 Grym Glow 2022 - Aceshop", ["grym"]],
  ["MVP Neutron Energy - Aceshop", ["energy"]],
  ["Origio Harp - Aceshop", ["harp"]],
  ["Z-Line Buzzz SS Paige Shue Signature Series - Aceshop", ["buzzz-ss"]],
  ["Halo Star Beast - Aceshop", ["beast"]],
  ["SL Neutron Ascend - Aceshop", ["ascend"]],
  ["SL Cosmic Neutron Drift - Aceshop", ["drift"]],
  ["SL Cosmic Neutron Flare - Aceshop", ["flare"]],
  ["SL Cosmic Neutron Runway - Aceshop", ["runway"]],
  ["SL Electron Pilot (Soft) - Aceshop", ["pilot"]],
  ["SL Electron Pilot (Firm) - Aceshop", ["pilot"]],
  ["K1 Krut - Aceshop", ["krut"]],
  ["SL Neutron Trace - Aceshop", ["trace"]],
  ["SL Electron Pilot - Aceshop", ["pilot"]],
  ["Active Premium Magician - Aceshop", ["magician"]],
  ["Axiom Cosmic Electron Proxy Medium - Aceshop", ["proxy"]],
  ["MVP Electron Atom Firm - Aceshop", ["atom"]],
  ["MVP Cosmic Neutron Volt - Aceshop", ["volt"]],
  ["Axiom Cosmic Electron Envy Medium - Aceshop", ["envy"]],
  ["Active Premium Majesty  - Aceshop", ["majesty"]],
  ["Putter Line Challenger - Aceshop", ["challenger"]],
  ["Gold River - Aceshop", ["river"]],
  ["Axiom Cosmic Electron Proxy Soft - Aceshop", ["proxy"]],
  ["Axiom Cosmic Electron Proxy Firm - Aceshop", ["proxy"]],
  ["Axiom Eclipse Envy Glow - Aceshop", ["envy"]],
  ["Axiom Neutron Crave - Sarah Hokom Signature Series - Aceshop", ["crave"]],
  ["Lucid Evader First Run - Aceshop", ["evader"]],
  ["Star Wraith Bottom Stamp - Aceshop", ["wraith"]],
  ["KC-Pro Roc - Aceshop", ["roc"]],
  ["K1 Stål Glow 2022 - Aceshop", ["stal"]],
  ["Star Wraith Nathan Queen 2021 - Aceshop", ["wraith"]],
  ["Royal Grand Rive First Run - Aceshop", ["rive"]],
  ["Royal Faith Sense First run - Aceshop", ["faith"]],
  ["MVP Neutron Reactor - Aceshop", ["reactor"]],
  ["K1 Järn - Aceshop", ["jarn"]],
  ["Active Sensei - Aceshop", ["sensei"]],
  ["Putter Line Soft Magnet - Aceshop", ["magnet"]],
  ["Star Destroyer Philo Brathwaite 2021 - Aceshop", ["destroyer"]],
  ["Spirit Diamond - Aceshop", ["spirit"]],
  ["Putter Line Soft Banger-GT - Aceshop", ["banger-gt"]],
  ["Zero Pure Hard - Aceshop", ["pure"]],
  ["Gold Sapphire - Aceshop", ["sapphire"]],
  ["K1 Reko Glow 2023 - Aceshop", ["reko"]],
  ["Opto Fuse - Aceshop", ["fuse"]],
  ["Opto Chameleon Ballista - Aceshop", ["ballista"]],
  ["Putter Line Banger-GT - Aceshop", ["banger-gt"]],
  ["K1 Lots Glow 2023 - Aceshop", ["lots"]],
  ["K3 Berg Hard - Aceshop", ["berg"]],
  ["MVP Neutron Nitro - Aceshop", ["nitro"]],
  [
    "Lucid-X Glimmer Sergeant - Paige Shue Team Series 2021 - Aceshop",
    ["sergeant"],
  ],
  ["Hybrid Warden -  A.J. Risley Team Series 2021 - Aceshop", ["warden"]],
  ["Eco Pure - Aceshop", ["pure"]],
  ["Active Premium Rockstar - Aceshop", ["rockstar"]],
  ["Prime Burst Judge - Aceshop", ["judge"]],
  ["MVP Neutron Signal - Aceshop", ["signal"]],
  ["Star Mako3 Kona Panis Tour Series - Aceshop", ["mako3"]],
  ["Evolution Neo Mutant - Aceshop", ["mutant"]],
  ["Opto Explorer - Aceshop", ["explorer"]],
  ["Wizard Super stupid soft - Aceshop", ["wizard"]],
  ["Wizard pure white, Firm - Aceshop", ["wizard"]],
  ["Big Z Zeus - Aceshop", ["zeus"]],
  ["Team Aceshop Star Wraith", ["wraith"]],
  ["300 M2 - Aceshop", ["m2"]],
  ["MVP Electron Nomad Medium - James Conrad Edition - Aceshop", ["nomad"]],
  ["Big Z Thrasher - Aceshop", ["thrasher"]],
  ["M Model S DuraFlex - Aceshop", ["m-model-s"]],
  ["Z-Line Crank SS - Aceshop", ["crank-ss"]],
  ["Opto-X Havoc - Aceshop", ["havoc"]],
  ["Putter Line Challenger OS - Aceshop", ["challenger"]],
  ["Westside Discs VIP Adder", ["adder"]],
  ["Magic Lightweight SureGrip m/ Aceshop logo", ["magic"]],
  ["K3 Reko Hard - Aceshop", ["reko"]],
  ["Z-Line Flick - Aceshop", ["flick"]],
  ["Nexus Firefly Nate Sexton 2021 - Aceshop", ["firefly"]],
  ["ESP Undertaker 6x Paul McBeth Signature Series - Aceshop", ["undertaker"]],
  ["C-Line FD3 Jackal - Aceshop", ["fd3"]],
  ["Magic Firm m/ Aceshop logo", ["magic"]],
  ["Grand Grace - Aceshop", ["grace"]],
  ["Z-Line Nuke OS - Aceshop", ["nuke"]],
  ["Big Z Vulture - Aceshop", ["vulture"]],
  ["BT Swan2 Soft - Aceshop", ["swan-2"]],
  ["BT Swan2 Medium - Aceshop", ["swan-2"]],
  ["Z-Line Fly Dye Sol - Aceshop", ["sol"]],
  ["Champion Valkyrie - Aceshop", ["valkyrie"]],
  ["Star Sidewinder - Aceshop", ["sidewinder"]],
  ["Opto Claymore - Aceshop", ["claymore"]],
  ["K1 Berg - Aceshop", ["berg"]],
  [
    "S-Line PD Nordic Phenom - Niklas Anttila Signature Series Special Blend - Aceshop",
    ["pd"],
  ],
  ["BT Burst Harp Hard - Aceshop", ["harp"]],
  ["Star Destroyer SockiBot - Aceshop", ["destroyer"]],
  ["Star Tl3 - Aceshop", ["tl3"]],
  ["Champion Roc3 Henna Blomroos Tour Series 2021 - Aceshop", ["roc3"]],
  ["Evolution Neo Method - Aceshop", ["method"]],
  ["Innova Star Gator", ["gator"]],
  ["Innova Pro Shryke", ["shryke"]],
  ["Big Z Force - Aceshop", ["force"]],
  ["MVP Electron Atom Medium - Aceshop", ["atom"]],
  ["R-Pro Hydra - Aceshop", ["hydra"]],
  ["MVP Plasma Servo - Aceshop", ["servo"]],
  ["750 H2 v2 - Aceshop", ["h2-v2"]],
  ["Solid White ESP Buzzz Bottom Stamp - Aceshop", ["buzzz"]],
  ["Solid White ESP Roach Bottom Stamp - Aceshop", ["roach"]],
  ["Latitude Gold Burst Sapphire", ["sapphire"]],
  ["750 H3v2 - Aceshop", ["h3-v2"]],
  ["DISCRAFT PAUL MCBETH BIG Z LUNA - Aceshop", ["luna"]],
  ["DX Dart - Aceshop", ["dart"]],
  ["DX Destroyer - Aceshop", ["destroyer"]],
  ["DX Cheetah - Aceshop", ["cheetah"]],
  ["DX Viking - Aceshop", ["viking"]],
  ["Divergent StayPut Golem", ["golem"]],
  ["TITANIUM BUZZZ - Aceshop", ["buzzz"]],
  ["Z-Line Vulture - Aceshop", ["vulture"]],
  ["JK Pro Aviar-X - Aceshop", ["aviar-x"]],
  ["Axiom Neutron Rhythm - Aceshop", ["rhythm"]],
  ["Halo Star Thunderbird Jeremy Koling 2023 - Aceshop", ["thunderbird"]],
  ["Halo Star Thunderbird - Aceshop", ["thunderbird"]],
  ["Halo Star Aero 40th Anniversary - Aceshop", ["aero"]],
  ["Star Alien - Aceshop", ["alien"]],
  ["SL Neutron Runway - Aceshop", ["runway"]],
  ["MVP Neutron Photon - Aceshop", ["photon"]],
  ["Royal Prototype Grand Glory - Aceshop", ["glory"]],
  ["2022 Paige Pierce Tour Series Fierce - Aceshop", ["fierce"]],
  ["Latitude 64 Grand Royal Trust", ["trust"]],
  ["Innova Champion Rhyno", ["rhyno"]],
  ["SL Cosmic Neutron Lift - Aceshop", ["lift"]],
  ["Gold Orbit Pure Kristin Tattar 2023 European Champion - Aceshop", ["pure"]],
  ["Z-Line Zone OS - Aceshop", ["zone"]],
  ["ESP Zone - Aceshop", ["zone"]],
  ["Champion Power Disc Phantom Sword - Aceshop", ["phantom-sword"]],
  ["K1 Reko X - Aceshop", ["reko-x"]],
  ["Infinite I-Blend Czar", ["czar"]],
  ["Metal Flake Champion Max James Proctor 2022 - Aceshop", ["max"]],
  ["VIP-X Moonshine Harp - Ricky Wysocki Sockibomb Stamp - Aceshop", ["harp"]],
  ["Opto Mercy - Lauri Lehtinen 2022 Team Series - Aceshop", ["mercy"]],
  ["Crystal Line Snoopy First Run - Aceshop", ["snoopy"]],
  ["K3 Reko-X - Aceshop", ["reko-x"]],
  ["Innova Star Mamba", ["mamba"]],
  ["Fuzion Orbit Escape Kona Panis - Aceshop", ["ape"]],
  ["MVP Electron Matrix - Aceshop", ["matrix"]],
  ["Alpha-Solid Silicon Founders Edition - Aceshop", ["silicon"]],
  ["K1 Lots - Aceshop", ["lots"]],
  ["S-Line MD3 - Aceshop", ["md3"]],
  ["S-Line P2 - Aceshop", ["p2"]],
  ["Champion Thunderbird - Aceshop", ["thunderbird"]],
  ["Halo Star Invader - Aceshop", ["invader"]],
  ["K1 Falk - Aceshop", ["falk"]],
  ["Star Destroyer Bottom Stamp - Aceshop", ["destroyer"]],
  ["Star Alien Innova Star - Aceshop", ["alien"]],
  ["ESP Anax Paul McBeth - Aceshop", ["anax"]],
  ["Z-Line Buzzz - Aceshop", ["buzzz"]],
  ["S-line DD3 - Aceshop", ["dd3"]],
  ["Stupid Tree - Alfa Discs Chrome Apollo", ["apollo"]],
  ["Evolution Neo Instinct - Aceshop", ["instinct"]],
  ["Jawbreaker Roach - Aceshop", ["roach"]],
  ["Jawbreaker Zone - Aceshop", ["zone"]],
  ["5X PAIGE PIERCE Z SOL - Aceshop", ["sol"]],
  ["Z LINE AVENGER SS - Aceshop", ["avenger-ss"]],
  ["Z-Line Buzzz OS - Aceshop", ["buzzz-os"]],
  ["R-Pro Rhyno - Aceshop", ["rhyno"]],
  ["Star Leopard - Aceshop", ["leopard"]],
  ["Tour Series Color Glow Pro Roc3  - Aceshop", ["roc3"]],
  ["Champion Teebird3 Ricky Wysocki - Aceshop", ["teebird3"]],
  ["DX Dragon - Aceshop", ["dragon"]],
  ["Kastaplast K1 Glow Berg", ["berg"]],
  ["Star Firebird - Aceshop", ["firebird"]],
  ["Star Wraith - Aceshop", ["wraith"]],
  ["BT Crown Medium - Aceshop", ["crown"]],
  ["Star Valkyrie - Aceshop", ["valkyrie"]],
  ["Pro Boss - Aceshop", ["boss"]],
  ["Champion Xcaliber - Aceshop", ["xcaliber"]],
  ["Star Leopard3 - Aceshop", ["leopard3"]],
  ["VIP Gatekeeper  - Aceshop", ["gatekeeper"]],
  ["Z-LINE THRASHER - Aceshop", ["thrasher"]],
  ["Star Katana - Aceshop", ["katana"]],
  ["Discmania Evolution Exo Link Hard - Aceshop", ["link"]],
  ["R-Pro Dart - Aceshop", ["dart"]],
  ["Evolution Neo Enigma - Aceshop", ["enigma"]],
  ["ESP Malta Midrange - Aceshop", ["malta"]],
  ["Star TL - Aceshop", ["tl"]],
  ["Opto Musket - Aceshop", ["musket"]],
  ["Opto Compass - Aceshop", ["compass"]],
  ["Z-Line Nuke SS - Aceshop", ["nuke-ss"]],
  ["Z-Line Nuke - Aceshop", ["nuke"]],
  ["Discmania Evolution Exo Method Hard - Aceshop", ["method"]],
  ["ESP FORCE PAUL MCBETH SIGNATURE SERIES - Aceshop", ["force"]],
  ["Axiom Neutron Excite - Aceshop", ["excite"]],
  [
    "Axiom Electron Envy Firm - James Conrad Signature Series - Aceshop",
    ["envy"],
  ],
  ["MVP Fission Volt - Aceshop", ["volt"]],
  ["Evolution Exo Logic Hard - Aceshop", ["logic"]],
  ["Putter Line Soft Challenger - Aceshop", ["challenger"]],
  ["Active Shogun - Aceshop", ["shogun"]],
  ["Royal Grand Trust first run - Aceshop", ["trust"]],
  ["K3 Kaxe - Aceshop", ["kaxe"]],
  ["VIP Adder First Run - Aceshop", ["adder"]],
  ["BT Burst Swan2 Soft - Aceshop", ["swan-2"]],
  ["Champion Ape - Aceshop", ["ape"]],
  ["MVP Proton Volt - Aceshop", ["volt"]],
  ["Fuzion Orbit Felon Ricky Wysocki - Aceshop", ["felon"]],
  ["SL Cosmic Neutron Trace Sarah Hokom Signature Series - Aceshop", ["trace"]],
  [
    "Swirly S-Line FD - Eagle McMahon & Ella Hansen Triumph Series 2023 Discmania Open Champion - Aceshop",
    ["fd"],
  ],
  ["dgputt pakke - K3 Reko - 5 pakk - Aceshop", ["reko"]],
  ["dgputt pakke - Electron Pilot Medium - 3 pakk - Aceshop", ["pilot"]],
  ["dgputt pakke - Electron Pilot Medium - 5 pakk - Aceshop", ["pilot"]],
  ["Z-Line Cicada - First Run - Aceshop", ["cicada"]],
  ["Horizon S-Line MD1 Special Edition - Aceshop", ["md1"]],
  ["S-Line Swirl FD Special Edition - Aceshop", ["fd"]],
  ["dgputt pakke - Royal Faith Sense First run - 5 pakk - Aceshop", ["faith"]],
  ["LIMITED EDITION 2023 HALLOWEEN BUZZZ SUPERCOLOR - Aceshop", ["buzzz"]],
  ["Latitude Grand Orbit Grace Kristin Tattar World Champion 2023", ["grace"]],
  ["Innova Pro Beast", ["beast"]],
  ["Innova Star Alien", ["alien"]],
  ["Phoenix Midrange SHU Yikun - GolfKongen", ["shu"]],
  ["DX Aviar PT & AP Innova - GolfKongen", ["aviar"]],
  ["Innova Star Wraith", ["wraith"]],
  [
    "Origin Geo Midrange Driver assortert farge Discmania - GolfKongen",
    ["origin"],
  ],
  ["Majesty Active Premium Driver Discmania - GolfKongen", ["majesty"]],
  ["Glitch Neutron Soft Putter MVP - GolfKongen", ["glitch"]],
  ["Nomad Electron Putter assortert farge MVP - GolfKongen", ["nomad"]],
  ["Sensei Putter Discmania - GolfKongen", ["sensei"]],
  ["Z Buzzz Midrange assortert farge Discraft - GolfKongen", ["buzzz"]],
  ["Crystal Line Midrange Apollo Alfa Discs - GolfKongen", ["apollo"]],
  ["Crystal Line Putter Snoopy  Alfa Discs - GolfKongen", ["snoopy"]],
  ["Scorch Driver assortert farge Discraft - GolfKongen", ["scorch"]],
  ["Origio Burst Tursas Midrange Latitude64 - GolfKongen", ["tursas"]],
  ["Crystal Line Driver Cosmic Alfa Discs - GolfKongen", ["cosmic"]],
  [
    "Titanium Undertaker Driver assortert farge Discraft - GolfKongen",
    ["undertaker"],
  ],
  ["ESP Malta Midrange assortert farge Discraft - GolfKongen", ["malta"]],
  ["ESP Nuke Driver assortert farge Discraft - GolfKongen", ["nuke"]],
  ["Dragon Line View Driver Yikun - GolfKongen", ["view"]],
  ["VIP Underworld Driver Latitude64 - GolfKongen", ["underworld"]],
  ["Dragon Line Gui Putter Yikun - GolfKongen", ["gui"]],
  ["Retro Burst River Driver Latitude64 - GolfKongen", ["river"]],
  ["Glacier Line Mad Mission Midrange Guru - GolfKongen", ["mad-mission"]],
  ["Glacier Line Flow Motion Putt Guru - GolfKongen", ["flow-motion"]],
  ["Zero Medium Keystone Putt Latitude64 - GolfKongen", ["keystone"]],
  ["Royal Grand Rive Driver Latitude64 - GolfKongen", ["rive"]],
  ["Discmania EXO Hard Logic", ["logic"]],
  ["Innova Champion Savant", ["savant"]],
  ["Pro KC-PRO Putt assortert farge Innova - GolfKongen", ["aviar"]],
  ["ESP Buzzz Midrange assortert farge Discraft - GolfKongen", ["buzzz"]],
  ["Origio Burst Underworld Driver Latitude64 - GolfKongen", ["underworld"]],
  ["Gateway Platinum Illusion", ["illusion"]],
  ["BT Burst Swan 1 Reborn Hard - Aceshop", ["swan-1-reborn"]],
  ["Opto Stiletto - Aceshop", ["stiletto"]],
  ["Champion Gator Metal Flake - Aceshop", ["gator"]],
  ["MVP Neutron Relativity - Aceshop", ["relativity"]],
  ["Classic Deputy Blend - Aceshop", ["deputy"]],
  ["Discraft ESP Nuke Paige Pierce", ["nuke"]],
  ["Classic Burst Deputy Blend - Aceshop", ["deputy"]],
  ["Zero Pure Medium - Aceshop", ["pure"]],
  ["Active Magician - Aceshop", ["magician"]],
  ["Innova Star Destroyer Liverbird-Edition", ["destroyer"]],
  ["Innova Star AviarX3", ["aviarx3"]],
  ["Latitude 64 Orbit Grand Trust", ["trust"]],
  ["DX Aviar PT & AP Bottom Stamp - Aceshop", ["aviar"]],
  ["Fuzion Sergeant - Aceshop", ["sergeant"]],
  ["Champion Beast - Aceshop", ["beast"]],
  ["MVP Neutron Teleport - Aceshop", ["teleport"]],
  ["Axiom Electron Proxy Firm - Aceshop", ["proxy"]],
  ["Chrome line Apollo - Aceshop", ["apollo"]],
  ["Crystal Line Apollo - First Run - Aceshop", ["apollo"]],
  ["Midrange Leviathan - Aceshop", ["leviathan"]],
  ["ESP Scorch - Aceshop", ["scorch"]],
  ["Putter Line Soft Roach - Aceshop", ["roach"]],
  ["Big Z Malta - Aceshop", ["malta"]],
  ["ESP Nuke OS - Aceshop", ["nuke"]],
  ["Star Eagle Gregg Barsby Tour Series 2021 - Aceshop", ["eagle"]],
  ["Axiom Neutron Insanity - Aceshop", ["insanity"]],
  ["Crystal Line Apollo - Aceshop", ["apollo"]],
  ["MVP Electron Ion medium - Aceshop", ["ion"]],
  ["MVP Neutron Resistor - Aceshop", ["resistor"]],
  ["Z-Line Scorch - Aceshop", ["scorch"]],
  ["K1 Rask Luke Samson Tour Series - Aceshop", ["rask"]],
  [
    "Axiom Electron Envy Medium - James Conrad Signature Series - Aceshop",
    ["envy"],
  ],
  ["MVP Cosmic Neutron Entropy - Aceshop", ["entropy"]],
  ["Putter Narwhal - Aceshop", ["narwhal"]],
  [
    "Nathan Queen Thunderbird � DGPT Champion � Star - Aceshop",
    ["thunderbird"],
  ],
  ["M Model S BaseGrip - Aceshop", ["m-model-s"]],
  ["Hybrid Moonshine Warden � AJ Risley Team Series - Aceshop", ["warden"]],
  ["D Model OS DuraFlex - Aceshop", ["d-model-os"]],
  ["Axiom Neutron Mayhem - Aceshop", ["mayhem"]],
  ["Midrange Kapre - Aceshop", ["kapre"]],
  ["MVP Electron Atom Soft - Aceshop", ["atom"]],
  ["D Model US DuraFlex - Aceshop", ["d-model-us"]],
  ["Axiom Electron Proxy Soft - Aceshop", ["proxy"]],
  ["Driver Basilisk - Aceshop", ["basilisk"]],
  ["MVP Electron Anode - Aceshop", ["anode"]],
  ["K1 Reko Soft - Aceshop", ["reko"]],
  ["Classic Blend Emac Judge - Aceshop", ["emac-judge"]],
  ["BT Burst Swan2 Medium - Aceshop", ["swan-2"]],
  ["Ethereal Votum - Aceshop", ["votum"]],
  ["BT Burst Swan2 Hard - Aceshop", ["swan-2"]],
  ["Ethos Praxis - Aceshop", ["praxis"]],
  ["500 X3 - Aceshop", ["x3"]],
  [
    "Axiom Electron Envy Soft - James Conrad Signature Series - Aceshop",
    ["envy"],
  ],
  ["Driver Kraken - Aceshop", ["kraken"]],
  ["400G M3 - Aceshop", ["m3"]],
  ["Axiom Electron Proxy - Aceshop", ["proxy"]],
  ["Alfa Discs Crystal Snoopy", ["snoopy"]],
  ["300 PX-3 Prototype - Aceshop", ["px-3"]],
  ["Prodigy 400 FX-2", ["fx-2"]],
  ["XT Rhyno X - Aceshop", ["rhyno-x"]],
  ["Gold Ice Compass - Aceshop", ["compass"]],
  ["Alfa Discs Crystal Apollo", ["apollo"]],
  ["PAIGE PIERCE PASSION - Aceshop", ["passion"]],
  [
    "Classic Supreme Orbit Sockibomb Slammer First Run - Aceshop",
    ["sockibomb-slammer"],
  ],
  ["Innova Pro Wraith", ["wraith"]],
  ["K1 Järn Fundraiser Heatland Open 2022 - Aceshop", ["jarn"]],
  ["2022 Chandler Fry Tour Series Surge - Aceshop", ["surge"]],
  ["750 FX-2 - Aceshop", ["fx-2"]],
  ["Opto Chameleon Core - Aceshop", ["core"]],
  ["Ethos Omen - Aceshop", ["omen"]],
  ["Lux Instinct Special Edition - Aceshop", ["instinct"]],
  ["Ethos Votum - Aceshop", ["votum"]],
  ["Innova Star Caiman", ["caiman"]],
  ["XT Dart - Aceshop", ["dart"]],
  ["500 M1 - Aceshop", ["m1"]],
  ["Innova Champion Caiman", ["caiman"]],
  ["Sir Alex F. EV-7 Mobius", ["mobius"]],
  ["D-Line P2 Flex 2 - Aceshop", ["p2"]],
  ["Discraft Esp Avenger SS Paul McBeth", ["avenger-ss"]],
  ["Latitude Gold Ballista", ["ballista"]],
  ["Innova Halo Star Aero-Innova 40th Anniversary", ["aero"]],
  ["K3 Reko X", ["reko-x"]],
  ["Latitude Opto Ice XXX", ["xxx"]],
  ["Lucid Raider Ricky Wysocki Sockibomb Stamp - Aceshop", ["raider"]],
  ["Ethos Synapse - Aceshop", ["synapse"]],
  ["Innova Champion Daedalus", ["daedalus"]],
  ["Innova Champion Roc3", ["roc3"]],
  ["Innova Star Firebird", ["firebird"]],
  ["2022 Ezra Aderhold Tour Series Nuke - Aceshop", ["nuke"]],
  ["Discraft Esp Hades Paul McBeth", ["hades"]],
  ["Discmania Exo Hard Method", ["method"]],
  ["Discmania Neo Enigma", ["enigma"]],
  ["Dynamic Discs Classic Blend Judge", ["judge"]],
  ["Prodigy 400 Falcor", ["falcor"]],
  ["Jordan H. Innova Star Roadrunner", ["roadrunner"]],
  ["Infinite D-Blend Alpaca", ["alpaca"]],
  ["K3 Svea Hard - Aceshop", ["svea"]],
  ["Prodigy 400 Shadowfax Proto Stamp", ["shadowfax"]],
  ["Nebula Ethereal Animus - Aceshop", ["animus"]],
  ["Discmania Neo Method", ["method"]],
  ["Kastaplast K1 Vass", ["vass"]],
  ["Dynamic Discs Lucid Truth", ["truth"]],
  ["Opto-X Culverin - Aceshop", ["culverin"]],
  ["K1 Lots", ["lots"]],
  ["Prodigy 400 F9", ["f9"]],
  ["Discmania NEO Instinct", ["instinct"]],
  ["Innova Star FL", ["fl"]],
  ["Westside BT Hard Harp", ["harp"]],
  ["Discraft Z Zone Paul McBeth", ["zone"]],
  ["Sir Alex F. Alfa Discs Apollo", ["apollo"]],
  ["Opto Glimmer Anchor - Aceshop", ["anchor"]],
  ["Westside VIP Underworld", ["underworld"]],
  ["Latitude 64 Zero Hard Dagger", ["dagger"]],
  ["Innova DX Sonic", ["sonic"]],
  ["Lucid Evader Ricky Wysocki Sockibomb Stamp - Aceshop", ["evader"]],
  ["Innova Halo Star Aviar", ["aviar"]],
  ["Prodigy 400 D2", ["d2"]],
  ["Discmania EXO Hard Tactic", ["tactic"]],
  ["Discraft ESP Anax Paul McBeth", ["anax"]],
  ["Latitude 64 Opto Sapphire", ["sapphire"]],
  ["Kastaplast K1 Falk", ["falk"]],
  ["Discmania Active Premium Rockstar", ["rockstar"]],
  ["Prodigy 400 D3", ["d3"]],
  ["ESP Nuke SS - Aceshop", ["nuke-ss"]],
  ["Discmania EXO Soft Tactic", ["tactic"]],
  ["Prodigy 400 D4", ["d4"]],
  ["Discraft Paige Pierce Z Sol", ["sol"]],
  ["Zero Hybrid Moonshine Keystone - Aceshop", ["keystone"]],
  ["Axiom Neutron Defy - Aceshop", ["defy"]],
  ["Innova Champion Eagle", ["eagle"]],
  ["Innova Star Katana", ["katana"]],
  ["Discmania C-Line FD", ["fd"]],
  ["K1 Line Järn", ["jarn"]],
  ["Innova DX Classic Aviar", ["aviar"]],
  ["Lucid Enforcer Ricky Wysocki Sockibomb Stamp - Aceshop", ["force"]],
  ["400G M4 Cale Leiviska - Aceshop", ["m4"]],
  ["Innova JK Pro Aviar-X", ["aviar-x"]],
  ["K1 Lots Scott Stokely Tour Series", ["lots"]],
  ["Innova R-Pro Pig", ["pig"]],
  ["Discraft Z Mantis", ["mantis"]],
  ["Prodigy 400 Reverb", ["reverb"]],
  ["Axiom Fission Crave - Aceshop", ["crave"]],
  ["Streamline Electron Firm Pilot", ["pilot"]],
  ["Latitude 64 Opto Fuse", ["fuse"]],
  ["Gateway Organic Hemp Blend SS Element", ["element"]],
  ["Latitude 64 Gold Compass", ["compass"]],
  ["Streamline Soft Electron Pilot", ["pilot"]],
  ["Prodigy DuraFlex P Model S", ["p-model-s"]],
  ["Innova GStar Wraith", ["wraith"]],
  ["Gateway Hemp Blend Element", ["element"]],
  ["Streamline Electron Pilot", ["pilot"]],
  ["Limited Edition 2022 Champions Cup Buzzz  - Aceshop", ["buzzz"]],
  ["Gateway Diamond Hemp Blend Element", ["element"]],
  ["Gateway Superglow Element", ["element"]],
  ["Gateway Diamond Element", ["element"]],
  ["Prodigy 300 PX-3 First Run", ["px-3"]],
  ["Discmania Neo Mutant", ["mutant"]],
  ["Latitude 64 Opto Jade Lightweight", ["jade"]],
  ["DX Eagle - Aceshop", ["eagle"]],
  ["Snoopy Stock Stamp/First Run Butikk", ["snoopy"]],
  ["Latitude 64 Opto Pioneer", ["pioneer"]],
  ["Latitude 64 Opto Musket", ["musket"]],
  ["K1 Reko X", ["reko-x"]],
  ["Innova Star Destroyer", ["destroyer"]],
  ["Innova DX Dragon", ["dragon"]],
  ["Discraft Z Wasp", ["wasp"]],
  ["K1 Lots Charlie Goodpasture Team Series 2022", ["lots"]],
  ["K1 Soft Svea", ["svea"]],
  ["Star AviarX3 - Aceshop", ["aviarx3"]],
  ["K3 Kaxe", ["kaxe"]],
  ["Innova DX Roc3", ["roc3"]],
  ["Alfa Discs Crystal Cosmic", ["cosmic"]],
  ["K1 Grym X-Out", ["grym"]],
  ["ESP Zone Adam Hammes 2022", ["zone"]],
  ["Star Aviar3", ["aviar3"]],
  ["Axiom Proton Fireball - Aceshop", ["fireball"]],
  ["Innova Champion Destroyer", ["destroyer"]],
  ["Innova Star Invader", ["invader"]],
  ["Innova Pro Destroyer", ["destroyer"]],
  ["Innova Champion Hawkeye", ["hawkeye"]],
  ["K1 Kaxe Z X-Out", ["kaxe-z"]],
  ["Innova Star Charger", ["charger"]],
  ["Innova Metal Flake Champion Teebird", ["teebird"]],
  ["Innova DX Bottom Stamp Roc", ["roc"]],
  ["500 F3 - Aceshop", ["f3"]],
  ["Innova Star Tern", ["tern"]],
  ["I-Blend Alpaca", ["alpaca"]],
  ["Innova DX Polecat", ["polecat"]],
  ["Innova Champion Wraith", ["wraith"]],
  ["Innova Star Eagle InnVision", ["eagle"]],
  ["Innova DX Gator", ["gator"]],
  ["Innova Star Wraith InnVision", ["wraith"]],
  ["Innova Star InnVision Destroyer", ["destroyer"]],
  ["Innova DX Roc", ["roc"]],
  ["Z line Surge SS - Aceshop", ["surge-ss"]],
  ["Ethereal Synapse - Aceshop", ["synapse"]],
  ["Halo Star Leopard3 - Ohn Scoggins 2022 - Aceshop", ["leopard3"]],
  ["Star Destroyer Custom - Aceshop", ["destroyer"]],
  ["Halo Star Wraith Garrett Gurthie 2022 - Aceshop", ["wraith"]],
  ["Star Wraith Custom - Aceshop", ["wraith"]],
  ["Champion Valkyrie Glow - Aceshop", ["valkyrie"]],
  ["Champion Glow Gator3 Joel Freeman 2022 - Aceshop", ["gator3"]],
  ["Champion Shryke Glow - Aceshop", ["shryke"]],
  ["Champion Hawkeye - Aceshop", ["hawkeye"]],
  ["Crystal Line Cosmic - Aceshop", ["cosmic"]],
  ["MVP Electron Terra Special Edition - Aceshop", ["terra"]],
  ["DX Shark - Aceshop", ["shark"]],
  ["Champion Tern Glow - Aceshop", ["tern"]],
  ["Axiom Fission Envy Special Edition - Aceshop", ["envy"]],
  ["Star Hawkeye - Aceshop", ["hawkeye"]],
  ["MVP Neutron Glitch Soft - Aceshop", ["glitch"]],
  [
    "Gold Orbit Saint Pro - Kristin Tattar 2022 World Champion - Aceshop",
    ["saint-pro"],
  ],
  ["DX Xero - Aceshop", ["xero"]],
  ["MVP Neutron Zenith Twisty James - Aceshop", ["zenith"]],
  ["Paige Pierce Crystal Sparkle Fierce - Aceshop", ["fierce"]],
  ["K1 Guld - Aceshop", ["guld"]],
  ["Classic Supreme Judge First Run - Aceshop", ["supreme-judge"]],
  ["Jawbreaker Zone OS - Aceshop", ["zone"]],
  ["DX Roc3 - Aceshop", ["roc3"]],
  ["Alpha-Solid Xenon - Founders Edition - Aceshop", ["xenon"]],
  ["Classic Blend Burst Guard - Aceshop", ["guard"]],
  ["Star Destroyer 15th Anniversary - Aceshop", ["destroyer"]],
  ["Pro D Brodie Smith Swirl Roach - Aceshop", ["roach"]],
  ["Champion Jay - Aceshop", ["jay"]],
  ["Star IT - Aceshop", ["it"]],
  ["ESP Sol - Aceshop", ["sol"]],
  ["Jeremy Koling Signature Star AviarX3 - Aceshop", ["aviarx3"]],
  ["XT Xero - Aceshop", ["xero"]],
  ["Ledgestone Z Swirl Tour Series Fierce - Aceshop", ["fierce"]],
  ["Ledgestone Andrew Marwede Swirl Tsunami - Aceshop", ["tsunami"]],
  ["Star Charger - Aceshop", ["charger"]],
  ["DX TL Glow - Aceshop", ["tl"]],
  ["Putter Line Soft Ringer - Aceshop", ["ringer"]],
  ["ESP Athena Paul McBeth Signatur Series - Aceshop", ["athena"]],
  [
    "Gold Orbit Claymore - Kristin Tattar Team Series 2023 - Aceshop",
    ["claymore"],
  ],
  ["Gold Pure - Aceshop", ["pure"]],
  ["Halo Star Firebird - Aceshop", ["firebird"]],
  ["Champion IT - Aceshop", ["it"]],
  [
    "Grand Orbit Grace - Kristin Tattar 2023 World Champion - Aceshop",
    ["grace"],
  ],
  ["K1 Reko X Glow 2023 - Aceshop", ["reko-x"]],
  ["Halo Star Roadrunner - Aceshop", ["roadrunner"]],
  ["K3 Berg X-Out - Aceshop", ["berg"]],
  ["Z-Line Fly Dye Zone - Aceshop", ["zone"]],
  ["Axiom Eclipse 2.0 Hex Simon Lizotte Halloween Edition - Aceshop", ["hex"]],
  ["C-Line FD Jackal - Aceshop", ["fd"]],
  ["Axiom Eclipse Proxy Special Edition - Aceshop", ["proxy"]],
  ["K1 Vass - Aceshop", ["vass"]],
  ["Volt Plasma Driver assortert farge MVP - GolfKongen", ["volt"]],
  ["MVP Neutron Orbital - Aceshop", ["orbital"]],
  ["dgputt pakke - BT Burst Swan 2 Hard - 3 pakk - Aceshop", ["swan-2"]],
  ["Axiom Fission Envy - Aceshop", ["envy"]],
  ["dgputt pakke - BT Swan2 Medium - 5 pakk - Aceshop", ["swan-2"]],
  ["Chrome Theios - Aceshop", ["theios"]],
  [
    "MVP R2 Eclipse Neutron Nomad - The Wolfman - Halloween 2023 - Aceshop",
    ["nomad"],
  ],
  ["Z-Line Fly Dye Buzzz SS - Aceshop", ["buzzz-ss"]],
  ["Axiom R2 Eclipse Neutron Crave - Rise of The Crave - Aceshop", ["crave"]],
  [
    "S-Line Vanguard Kyle Kline Creator Series Swirly Special Edition - Aceshop",
    ["vanguard"],
  ],
  ["Star Roc - Aceshop", ["roc"]],
  ["Halo Star Aviar Putt & Approach - Aceshop", ["aviar"]],
  ["Halo Star Savant - Aceshop", ["savant"]],
  ["Nexus Alien - Aceshop", ["alien"]],
  ["S-Line FD1 - Aceshop", ["fd1"]],
  ["S-Line FD3 - Aceshop", ["fd3"]],
  [
    "S-Line CD1 Zeta´s Moon - Colten Montgomery Signature Series Series Blend S-Line - Aceshop",
    ["cd1"],
  ],
  ["dgputt pakke - BT Swan2 Medium - 3 pakk - Aceshop", ["swan-2"]],
  ["dgputt pakke - Electron Pilot Firm - 3 pakk - Aceshop", ["pilot"]],
  ["dgputt pakke - Electron Pilot Firm - 5 pakk - Aceshop", ["pilot"]],
  ["MVP Neutron Watt - Aceshop", ["watt"]],
  ["dgputt pakke - BT Burst Swan 2 Hard - 5 pakk - Aceshop", ["swan-2"]],
  ["dgputt pakke - K3 Reko - 3 pakk - Aceshop", ["reko"]],
  ["Envy Plasma Putter assortert farge Axiom - GolfKongen", ["envy"]],
  ["Wave Neutron Driver assortert farge MVP - GolfKongen", ["wave"]],
  ["Fireball Proton Driver assortert farge Axiom - GolfKongen", ["fireball"]],
  ["Chrome Line Atlantis First Run - Aceshop", ["tl"]],
  ["dgputt pakke - Royal Faith Sense First run - 3 pakk - Aceshop", ["faith"]],
  [
    "Moonshine Explorer Driver Assortert farge Latitude64 - GolfKongen",
    ["explorer"],
  ],
  ["Z Heat Driver assortert farge Discraft - GolfKongen", ["heat"]],
  ["Big Z Hades Driver assortert farge Discraft - GolfKongen", ["hades"]],
  ["Tiger Line Kui Midrange Yikun - GolfKongen", ["kui"]],
  ["Greatful Dead Neo Splice (Steal Your Blood) - Aceshop", ["splice"]],
  ["Z Sol Midrange assortert farge Discraft - GolfKongen", ["sol"]],
  ["Genius Active Premium Driver Discmania - GolfKongen", ["genius"]],
  ["Mutant Neo Midrange assortert farge Discmania - GolfKongen", ["mutant"]],
  ["ESP Force Driver assortert farge Discraft - GolfKongen", ["force"]],
  ["Envy Electron Putter MVP - GolfKongen", ["envy"]],
  [
    "ESP Hades Distance Driver assortert farge Discraft - GolfKongen",
    ["hades"],
  ],
  ["LIMITED EDITION 2023 HALLOWEEN Z BUZZZ NITE GLO - Aceshop", ["buzzz"]],
  [
    "Z Undertaker Fairway Driver assortert farge Discraft - GolfKongen",
    ["undertaker"],
  ],
  ["Dragon Line Midrange YAN Yikun - GolfKongen", ["yan"]],
  ["Z Zone Putt assortert farge Discraft - GolfKongen", ["zone"]],
  ["Crystal Glow Line Midrange Apollo Alfa - GolfKongen", ["apollo"]],
  [
    "ESP Avenger SS Driver assortert farge Discraft - GolfKongen",
    ["avenger-ss"],
  ],
  ["Phoenix Putter XING Yikun - GolfKongen", ["xing"]],
  ["Fierce Paige Pierce assortert farge Discraft - GolfKongen", ["fierce"]],
  ["Z Buzzz SS Midrange assortert farge Discraft - GolfKongen", ["buzzz-ss"]],
  ["Moonshine Jade Driver Assortert farge Latitude64 - GolfKongen", ["jade"]],
  ["Terra Neutron Driver assortert farge MVP - GolfKongen", ["terra"]],
  ["Pro R-PRO Pig Putt assortert farge Innova - GolfKongen", ["pig"]],
  ["Big Z Luna assortert farge Discraft - GolfKongen", ["luna"]],
  ["Moonshine Fuse Midrange Assortert farge Latitude64 - GolfKongen", ["fuse"]],
  ["Crave Neutron Driver assortert farge MVP - GolfKongen", ["crave"]],
  ["Mayhem Proton Driver assortert farge Axiom - GolfKongen", ["mayhem"]],
  ["ESP Anax Driver assortert farge Discraft - GolfKongen", ["anax"]],
  ["Aurora Line Silent Cruiser Midrange Guru - GolfKongen", ["silent-cruiser"]],
  ["Glacier Line Short Slacker Driver Guru - GolfKongen", ["short-slacker"]],
  [
    "Champion Firebird Distance Driver assortert farge Innova - GolfKongen",
    ["firebird"],
  ],
  [
    "Star Teebird Fairway Driver Assortert farge Innova - GolfKongen",
    ["teebird"],
  ],
  ["C-Line PD Power Driver assortert farge Discmania - GolfKongen", ["pd"]],
  [
    "Champion Valkyrie Distance Driver assortert farge Innova - GolfKongen",
    ["valkyrie"],
  ],
  ["Star ROC3 Midrange assortert farge Innova - GolfKongen", ["roc3"]],
  ["Innova Star Cro", ["cro"]],
  [
    "Neo Enigma Distance Driver assortert farge Discmania - GolfKongen",
    ["enigma"],
  ],
  [
    "Star Destroyer Distance Driver assortert farge Innova - GolfKongen",
    ["destroyer"],
  ],
  ["Latitude 64 Zero Medium Keystone", ["keystone"]],
  [
    "Star Leopard Fairway Driver assortert farge Innova - GolfKongen",
    ["leopard"],
  ],
  ["Star Aviar X3 Putt assortert farge Innova - GolfKongen", ["aviar-x"]],
  ["Yikun Dragon Kui", ["kui"]],
  [
    "Champion Thunderbird Distance Driver assortert farge Innova - GolfKongen",
    ["thunderbird"],
  ],
  ["Divergent Narwhal", ["narwhal"]],
  ["D-line Flex 2 P2 Putt Discmania - GolfKongen", ["p2"]],
  ["Discmania Premium Active Magician", ["magician"]],
  ["Champion Mako3 Midrange assortert farge Innova - GolfKongen", ["mako3"]],
  ["Dynamic Discs Prime Judge", ["judge"]],
  ["Star Aviar Putt assortert farge Innova - GolfKongen", ["aviar"]],
  ["Prime Burst Emac Truth Midrange Latitude64 - GolfKongen", ["emac-truth"]],
  [
    "C-Line MD3 Midrange Driver assortert farge Discmania - GolfKongen",
    ["md3"],
  ],
  ["Infinite D-Blend Cohort", ["cohort"]],
  ["Opto Explorer Fairway Driver Latitude64 - GolfKongen", ["explorer"]],
  ["Champion Roc3 Midrange assortert farge Innova - GolfKongen", ["roc3"]],
  [
    "Star Wraith Distance Driver assortert farge Innova - GolfKongen",
    ["wraith"],
  ],
  ["Exo Logic Soft Putt assortert farge Discmania - GolfKongen", ["logic"]],
  ["Zero Medium Dagger Putt Latitude64 - GolfKongen", ["dagger"]],
  [
    "Exo Method Hard Midrange Driver assortert farge Discmania - GolfKongen",
    ["method"],
  ],
  ["Latitude 64 Opto Diamond", ["diamond"]],
  ["Royal Grand Midrange Trust Latitude64 - GolfKongen", ["trust"]],
  [
    "Champion Leopard Fairway Driver assortert farge Innova - GolfKongen",
    ["leopard"],
  ],
  ["K1 Göte", ["gote"]],
  ["ESP ZEUS Distance Driver assortert farge Discraft - GolfKongen", ["zeus"]],
  ["K3 Berg", ["berg"]],
  ["Jawbreaker Luna Putt assortert farge Discraft - GolfKongen", ["luna"]],
  ["Exo Logic Hard Putt assortert farge Discmania - GolfKongen", ["logic"]],
  [
    "Champion Teebird Fairway Driver assortert farge Innova - GolfKongen",
    ["teebird"],
  ],
  ["Infinite I-Blend Inca", ["inca"]],
  ["Innova Star Roadrunner Gregg Barsby", ["roadrunner"]],
  ["Star Leopard", ["leopard"]],
  ["Latitude 64 Opto Explorer", ["explorer"]],
  ["K1 Reko", ["reko"]],
  ["Gateway Discs Diamond Journey", ["diamond"]],
  ["Innova Champion Teebird", ["teebird"]],
  ["Latitude 64 Opto Pearl Lightweight", ["pearl"]],
  ["Innova GStar Destroyer", ["destroyer"]],
  ["Innova Champion Tl3", ["tl3"]],
  ["Innova Metal Flake Champion Roc3", ["roc3"]],
  ["Kastaplast K1 Glow Stål", ["stal"]],
  ["Westside Discs BT Soft Swan", ["swan-2"]],
  ["Discmania D-Line P2 Flex 2", ["p2"]],
  ["K1 Järn X-Out", ["jarn"]],
  ["Innova Yeti-Pro Aviar", ["aviar"]],
  ["Alfa Discs Chrome Line Apollo Moonlanding Stamp", ["apollo"]],
  ["Discraft Z Force Andrew Presnell 2021", ["force"]],
  ["Prodigy 400 F1", ["f1"]],
  ["Infinite I-Blend Dynasty", ["dynasty"]],
  ["Prodiscus Ultrium Troija", ["troija"]],
  ["Viking Storm Loki", ["loki"]],
  ["Viking Ground Rune", ["rune"]],
  ["Dynamic Discs Lucid Evader Ricky Wysocki", ["evader"]],
  ["Innova Star Firebird InnVision", ["firebird"]],
  ["Innova Star Toro Calvin Heimburg", ["toro"]],
  ["Zero Mercy Medium", ["mercy"]],
  ["K1 Lots X-out", ["lots"]],
  ["Innova DX Firebird", ["firebird"]],
  ["XT Xero", ["xero"]],
  ["Innova Champion Toro Calvin Heimburg", ["toro"]],
  ["Innova Star Bottom Stamp Wraith", ["wraith"]],
  ["Kastplast K1 Guld", ["guld"]],
  ["Latitude Grand Savior First Run", ["savior"]],
  ["Latitude Grand Savior Linus Carlsson 2023", ["savior"]],
  ["Kastaplast K1 Krut", ["krut"]],
  ["Alfa Discs Chrome Apollo Liverbird Edition", ["apollo"]],
  ["Corner Taken Quickly Alfa Discs Glow Cosmic", ["cosmic"]],
  ["Corner Taken Quickly Innova Star Firebird", ["firebird"]],
  [
    "Discmania Zeta's Moon Colten Montgomery Signature Series Special Blend S-Line CD1",
    ["cd1"],
  ],
  ["Jordan H. Gateway SS Magic", ["magic"]],
  ["Kastaplast K1 Soft Falk", ["falk"]],
  ["Innova Halo Star Roadrunner", ["roadrunner"]],
  ["Discmania S-Line FD3", ["fd3"]],
  ["Alfa Discs Chrome Atlantis First Run", ["tl"]],
  ["Innova First Run Star Alien", ["alien"]],
  ["K1 Soft Reko", ["reko"]],
  ["Latitude 64 Retro Line Compass", ["compass"]],
  ["Infinite I-Blend Ruin", ["ruin"]],
  ["Innova Star Teebird3", ["teebird3"]],
  ["Infinite I-Blend Pharaoh", ["pharaoh"]],
  ["Discmania Active Premium Majesty", ["majesty"]],
  ["Alfa Discs Chrome Cosmic", ["cosmic"]],
  ["K3 Järn", ["jarn"]],
  ["Latitude 64 Grand Grace", ["grace"]],
  ["K1 Kaxe", ["kaxe"]],
  ["K1 Stål", ["stal"]],
  ["Dynamic Discs Moonshine Warden Aj Risley 2021", ["warden"]],
  ["Prodigy 400 FX-3", ["fx-3"]],
  ["Viking Armor Loki", ["loki"]],
  ["Dynamic Discs Classic Supreme Slammer Raptor Eye", ["raptor"]],
  ["K1 Grym", ["grym"]],
  ["Dynamic Discs Fuzion Felon Raptor Eye", ["felon"]],
  ["Discraft Buzzz SS", ["buzzz-ss"]],
  ["Vortex Line Flow Motion Putt Guru - GolfKongen", ["flow-motion"]],
  [
    "Glacier Line Silent Cruiser Midrange Guru - GolfKongen",
    ["silent-cruiser"],
  ],
  [
    "Short Slacker Distance Driver assortert farge Guru - GolfKongen",
    ["short-slacker"],
  ],
  ["Innova Champion Leopard", ["leopard"]],
  ["Discmania Exo Soft Link", ["link"]],
  ["Latitude 64 Retro Pure", ["pure"]],
  ["Discraft Z Undertaker Paige Pierce", ["undertaker"]],
  ["Latitude 64 Opto Compass", ["compass"]],
  ["Latitude 64 Opto Saint", ["saint"]],
  ["Discraft ESP Force Paul McBeth", ["force"]],
  ["Dynamic Discs Prime Burst Truth Emac", ["truth"]],
  ["Infinite Halo S-Blend Exodus", ["exodus"]],
  ["Discmania GEO Essence", ["essence"]],
  ["Innova GStar Thunderbird", ["thunderbird"]],
  ["Eric Oakley - Metal Flake Glow C-Blend Exodus", ["exodus"]],
  ["Prodigy 750 FX-2", ["fx-2"]],
  ["Latitude 64 Eco Zero Pure", ["pure"]],
  ["Innova Halo Star Firebird", ["firebird"]],
  ["Innova Star Mako3 Liverbird Edition", ["mako3"]],
  ["Discmania Activ Premium Sensei", ["sensei"]],
  ["Latitude 64 Royal Rive", ["rive"]],
  ["Discmania C-Line PD", ["pd"]],
  ["Discmania Neo Paradigm", ["paradigm"]],
  ["Kastaplast K1 Glow Lots", ["lots"]],
  ["Discraft Jawbreaker Luna Paul McBeth", ["luna"]],
  ["Latitude Grand Savior", ["savior"]],
  ["Discmania S-Line DD3", ["dd3"]],
  ["Star Hawkeye", ["hawkeye"]],
  ["Kastaplast K1 Glow Reko X", ["reko-x"]],
  ["Westside VIP Anvil", ["anvil"]],
  ["Latitude 64 Gold-X Explorer Emerson Keith 2021", ["explorer"]],
  ["Discraft Big Z Malta", ["malta"]],
  ["Star Leopard3", ["leopard3"]],
  ["Innova Champion Shryke", ["shryke"]],
  ["Innova Jeremy Koling Tour Series Thunderbird", ["thunderbird"]],
  ["Latitude Gold Pure Kristin Tattar European Champion 2023", ["pure"]],
  ["K3 Hard Svea X-out", ["svea"]],
  ["Discmania S-Line FD1", ["fd1"]],
  ["Infinite Halo S-Blend Roman", ["roman"]],
  ["Kastaplast K1 Stig", ["stig"]],
  ["Latitude Opto Keystone", ["keystone"]],
  ["Innova Star Teebird", ["teebird"]],
  ["Retro Keystone", ["keystone"]],
  ["Dynamic Discs Lucid Raider Ricky Wysocki", ["raider"]],
  ["Innova Champion IT", ["it"]],
  ["Kastaplast K1 Krut Luke Samson TS 2023", ["krut"]],
  ["Discmania S-Line FD", ["fd"]],
  ["Latitude 64 Opto River", ["river"]],
  ["Innova XT Atlas", ["atlas"]],
  ["Kastaplast K1 Glow Göte", ["gote"]],
  ["Innova Halo Star Roc3", ["roc3"]],
  ["Discmania S-Line P2", ["p2"]],
  ["Kastaplast K1 Glow Svea", ["svea"]],
  ["Stupid Tree - EV7 Firm Penrose", ["penrose"]],
  ["Inova Halo Star Thunderbird", ["thunderbird"]],
  ["Discmania Horizon Sky Walker - Casey White FD1", ["fd1"]],
  ["Stupid Tree - Innova Star Wraith", ["wraith"]],
  ["K3 Hard Svea", ["svea"]],
  ["R-Pro Aviar - Aceshop", ["aviar"]],
  ["Active Premium Sensei - Aceshop", ["sensei"]],
  ["Discmania Evolution Exo Tactic Soft - Aceshop", ["tactic"]],
  ["K3 Reko - Aceshop", ["reko"]],
  ["5X Paige Pierce ESP Nuke - Aceshop", ["nuke"]],
  ["K1 Grym X - Aceshop", ["grym"]],
  ["BT Harp Hard - Aceshop", ["harp"]],
  ["Innova DX Aviar", ["aviar"]],
  ["Latitude 64 Sense Faith", ["faith"]],
  ["Discraft Esp Malta Paul McBeth", ["malta"]],
  ["Innova Nexus Alien", ["alien"]],
  ["Innova Champion Boss", ["boss"]],
  ["Discraft Z Thrasher", ["thrasher"]],
  ["Innova Champion Valkyrie", ["valkyrie"]],
  ["Innova DX Archangel", ["archangel"]],
  ["Innova Leopard3 Liverbird Edition", ["leopard3"]],
  ["K1 Svea", ["svea"]],
  ["Innova Star Roc3", ["roc3"]],
  ["Innova Star TL3", ["tl3"]],
  ["Discmania Active Premium Maestro", ["maestro"]],
  ["Discraft Esp Zeus Paul McBeth", ["zeus"]],
  ["Innova KC-Pro Roc", ["roc"]],
  ["K1 Rask", ["rask"]],
  ["Alfa Discs Chrome Apollo", ["apollo"]],
  ["Discmania Active Premium Astronaut", ["astronaut"]],
  ["Infinite I-Blend Exodus", ["exodus"]],
  ["Discmania S-Line MD3", ["md3"]],
  ["Discmania Neo Essence", ["essence"]],
  ["Gateway Diamond Wizard", ["wizard"]],
  ["Innova Star Wraith Liverbird Edition", ["wraith"]],
  ["K3 Reko", ["reko"]],
  ["Discraft Esp Stalker Paige Pierce", ["stalker"]],
  ["Innova Star Aviar", ["aviar"]],
  ["Innova Champion Teebird3", ["teebird3"]],
  ["Stupid Tree - EV7 Medium Penrose", ["penrose"]],
  ["Prodiscus Premium Troija", ["troija"]],
  ["Innova KC-Pro Aviar", ["aviar"]],
  ["Prodigy BaseGrip P-Model S", ["p-model-s"]],
];
